version: '3.8'

services:
  redis:
    image: bitnami/redis:8.0.2
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
